### PR TITLE
Fixed issue 31

### LINKED ISSUE #31: Consider alternatives to Thread.Sleep() in the shoot() method within the ShooterSubsystem

### PR DESCRIPTION
**Pull request by zbrotherton**
Should have changes to fix #31

### CODE REVIEW

File: src/main/java/frc/robot/commands/ShooterPrime.java [hunk 1]
```diff
@@ -23,30 +23,31 @@ public ShooterPrime(ShooterSubsystem shooterSubsystem) {
...
   }
 
   // Returns true when the command should end.
   @Override
   public boolean isFinished() {
     if(m_ShooterSubsystem.wheelReady()){
-      return true;
+      m_ShooterSubsystem.runCargo(true);
+      i++;
+      if(i==10){
```
Comment (caseyjbrotherton) [inline src/main/java/frc/robot/commands/ShooterPrime.java]: should put a quick comment here to remind us that it is expected to run for 10*20ms

**Review by caseyjbrotherton — APPROVED** [review]
