### PR TITLE
Merge competition changes

### LINKED ISSUE #222: Drivebase current limit is wrong on cc5
Drive base current limit was set at 50 amps, looks like it got bumped to 60. Should be at 50 amps

### PR DESCRIPTION
**Pull request by zbrotherton**
Will be tagged as cc6 on merge

### CODE REVIEW

**Comment by zbrotherton** [comment]
fixes #222

File: src/main/java/frc/robot/RobotContainer.java [hunk 1]
```diff
@@ -245,20 +243,20 @@ public void initAuton(Constants.Auton mode) {
...
       case PUSHTAXI: // the two taxis
       case INTAKETAXI:
-        if (driveBaseSubsystem != null && intakeSubsystem != null && cdsSubsystem != null) {
+        /* if (driveBaseSubsystem != null && intakeSubsystem != null && cdsSubsystem != null) {
           autonModes = new AutonModes(driveBaseSubsystem, intakeSubsystem, cdsSubsystem);
         } else {
           success = false;
         }
-        break;
+        break;*/
```
Comment (azvanderpas) [inline src/main/java/frc/robot/RobotContainer.java]: Lets fix this instead of leaving commented

File: src/main/java/frc/robot/commands/ShooterPressed.java [hunk 2]
```diff
@@ -50,7 +50,7 @@ public void execute() {
       // Otherwise, alignment is checked.
       if (i > 0 || !LLEnabled || m_LimelightSubsystem.calculatePID() == 0.0) {
         if (i == 0) {
-          m_CDSSubsystem.CDSBeltToggle(false);
+          m_CDSSubsystem.CDSBeltToggle(false, 0.95);
```
Comment (azvanderpas) [inline src/main/java/frc/robot/commands/ShooterPressed.java:53]: Constants for magic numbers

File: src/main/java/frc/robot/subsystems/CDSSubsystem.java [hunk 3]
```diff
@@ -175,6 +175,24 @@ public void CDSBeltToggle(boolean reverse) {
     }
   }
 
+  public void CDSBeltToggle(boolean reverse, double beltSpeed) {
```
Comment (azvanderpas) [inline src/main/java/frc/robot/subsystems/CDSSubsystem.java:160]: Change the other CDSBeltToggle to just call this one with the constant as the parameter

File: src/main/java/frc/robot/subsystems/ClimbSubsystem.java [hunk 4]
```diff
@@ -250,10 +271,16 @@ public void deployHA() {
     HaHeightOne = Constants.HaHeightMax;
     HaHeightTwo = Constants.HaHeightMax;
     m_HaOne.getPIDCtrl().setReference(HaHeightOne, CANSparkMax.ControlType.kPosition);
-    sbHaHeightOne.setNumber(HaHeightOne);
 
     m_HaTwo.getPIDCtrl().setReference(HaHeightOne, CANSparkMax.ControlType.kPosition);
-    sbHaHeightTwo.setNumber(HaHeightOne);
+  }
+
+  public void unlatchHA() {
```
Comment (azvanderpas) [inline src/main/java/frc/robot/subsystems/ClimbSubsystem.java]: Is this used at all?

**Review by azvanderpas — CHANGES_REQUESTED** [review]

File: src/main/java/frc/robot/subsystems/ClimbSubsystem.java (hunk 4 above)
Comment (zbrotherton) [reply src/main/java/frc/robot/subsystems/ClimbSubsystem.java]: No, since our PID isn't tuned correctly
Removing it

File: src/main/java/frc/robot/RobotContainer.java (hunk 1 above)
Comment (zbrotherton) [reply src/main/java/frc/robot/RobotContainer.java]: Do you want me to remove the second constructor? Or is there a different fix we should use

Comment (azvanderpas) [reply src/main/java/frc/robot/RobotContainer.java]: Actually just delete these lines and always use the constructor with all subsystems

Comment (zbrotherton) [reply src/main/java/frc/robot/RobotContainer.java]: Sounds good, deleting it all

File: src/main/java/frc/robot/Constants.java [hunk 5]
```diff
@@ -27,7 +27,8 @@ public AimModes previous() {
     },
     EJECT(2500.0, 0.0),
     LAUNCH(0.0, 0.0),
-    TARMAC(2530.0, 0.0),
+    TARMAC(2480.0, 0.0),
+    ATARMAC(2480.0, 0.0),
```
Comment (caseyjbrotherton) [inline src/main/java/frc/robot/Constants.java:31]: atarmac and tarmac are the same.  Were they meant to be different?

File: src/main/java/frc/robot/commands/ShooterPressed.java (hunk 2 above)
Comment (caseyjbrotherton) [reply src/main/java/frc/robot/commands/ShooterPressed.java:53]: You created a constant: CDSAutoBeltSpeed but you aren't using it, yet.

File: src/main/java/frc/robot/Constants.java (hunk 5 above)
Comment (zbrotherton) [reply src/main/java/frc/robot/Constants.java:31]: We added atarmac and tarmac as a way to change the auto ball speed and tele ball speed independently, as they are shooting differently somehow. This is part of a larger issue tracked as #224

Comment (caseyjbrotherton) [reply src/main/java/frc/robot/Constants.java:31]: But they arent different is my point.  So, wondering if you have a mistake here, and thought you were adjusting them differently...but weren't

Comment (zbrotherton) [reply src/main/java/frc/robot/Constants.java:31]: No, it's open to give us options should something go wrong, resolving this

**Review by azvanderpas — APPROVED** [review]
