### PR TITLE
Motor controller pid fix

### LINKED ISSUE #97: Autonomous Mode 2: One Ball Fender
- Start at fender
- Shoot preloaded cargo into fender 
- Leave tarmac
- Configurable delay (one value before, one value after)

### LINKED ISSUE #98: Autonomous Mode 3: Two Ball Fender
- Start at tape, line up with an external cargo. Will need two or more positions to avoid conflict with alliance 
- Collect ball while leaving tarmac
- Go back into tarmac 
- Align and shoot two cargo. Configurable between high and low goal (will need to end path at different locations)

### PR DESCRIPTION
**Pull request by tonyn10**

### CODE REVIEW

File: src/main/java/frc/robot/common/hardware/MotorController.java [hunk 1]
```diff
@@ -88,33 +82,34 @@ public void setPID() {
     mPIDController.setI(mI);
     mPIDController.setD(mD);
 
-    SmartDashboard.putNumber(mName + " P Value", mP);
-    SmartDashboard.putNumber(mName + " I Value", mI);
-    SmartDashboard.putNumber(mName + " D Value", mD);
-
-    SmartDashboard.putNumber(mName + " FF Value", mFF);
+    updateSmartDashboard(); // post onto smart dashboard
```
Comment (azvanderpas) [inline src/main/java/frc/robot/common/hardware/MotorController.java]: Running updateSmartDashboard() here will overwrite what was just written to the PID variables. I think if you keep the putNumber calls instead it'll fix the issue.

File: src/main/java/frc/robot/common/hardware/MotorController.java [hunk 2]
```diff
@@ -77,7 +71,7 @@ public double getSpeed() {
     return mEncoder.getVelocity();
   }
 
-  public void setPID() {
+  public void activatePID(double[] PID) {
```
Comment (azvanderpas) [inline src/main/java/frc/robot/common/hardware/MotorController.java]: Seems like this method should be private or get merged into setPID

File: src/main/java/frc/robot/common/hardware/MotorController.java [hunk 3]
```diff
@@ -88,33 +82,34 @@ public void setPID() {
...
-      if (SmartDashboard.getNumber(mName + " P Value", mP) != mP) {
-        mP = SmartDashboard.getNumber(mName + " P Value", mP);
+      // TODO: having a sole shuffleboard tab for PID tuning might be beneficical, there's a built
+      // in widget especially for PID
+
+      // check if values were updated in smart dashboard
+      // nothing in it at the start, assign it to value passed in earlier
+      double currentP = SmartDashboard.getNumber(mName + " P value", mP);
+      if (currentP != mP) {
+        mP = currentP;
```
Comment (azvanderpas) [inline src/main/java/frc/robot/common/hardware/MotorController.java:104]: This seems functionally the same as it was before. Why do we want to change this?

File: src/main/java/frc/robot/commands/AutonModes.java [hunk 4]
```diff
@@ -150,44 +153,50 @@ private void initializeRamseteCommands() {
...
                   limelightSubsystem,
                   cdsSubsystem,
                   true), // also has a time delay of 2-3 seconds
               new WaitCommand(Constants.delaytaxi),
-              oneBallRamseteCommand.beforeStarting(
-                  () -> driveBaseSubsystem.resetOdometry(oneBallTrajectory.getInitialPose())));
+              oneBallRamseteCommand
+                  .beforeStarting(
+                      () -> driveBaseSubsystem.resetOdometry(oneBallTrajectory.getInitialPose()))
+                  .andThen(() -> driveBaseSubsystem.stopDriveMotors()));
```
Comment (azvanderpas) [inline src/main/java/frc/robot/commands/AutonModes.java:180]: I think I noted this before, but if you do the beforeStarting and andThen parts as part of the getRamsetCommand method, then you don't have to add them everywhere (or worry about forgetting them).

File: src/main/java/frc/robot/commands/AutonModes.java [hunk 5]
```diff
@@ -54,6 +54,9 @@
   private Command threeBallCommand;
   private Command fourBallCommand;
 
+  // amount of time before starting auton
```
Comment (azvanderpas) [inline src/main/java/frc/robot/commands/AutonModes.java:57]: Units would be good (assuming seconds?)

File: src/main/java/frc/robot/subsystems/Tabs/TabDriveBase.java [hunk 6]
```diff
@@ -39,6 +42,14 @@ public TabDriveBase(DriveBaseSubsystem d) {
...
+    // This is the tab for controlling auton
+    sbWaitTimeSlider =
+        Shuffleboard.getTab("Auton")
+            .add("Max Speed", 1)
+            .withWidget(BuiltInWidgets.kNumberSlider)
+            .withProperties(Map.of("min", 1, "max", 10)) // specify widget properties here
+            .getEntry();
   }
 
   public void periodic() {
```
Comment (azvanderpas) [inline src/main/java/frc/robot/subsystems/Tabs/TabDriveBase.java:55]: Add @Override annotation

File: src/main/java/frc/robot/subsystems/Tabs/TabDriveBase.java [hunk 7]
```diff
@@ -55,6 +66,9 @@ public void periodic() {
       sbLeftPosition.setDouble(positions[0]); // in meters
       sbRightPosition.setDouble(positions[1]);
 
+      double waitTime = sbWaitTimeSlider.getDouble(1);
+      AutonModes.setWaitTime(waitTime);
```
Comment (azvanderpas) [inline src/main/java/frc/robot/subsystems/Tabs/TabDriveBase.java]:
```suggestion
      AutonModes.setWaitTime(sbWaitTimeSlider.getDouble(1));
```

**Review by azvanderpas — CHANGES_REQUESTED** [review]

File: src/main/java/frc/robot/commands/AutonModes.java [hunk 8]
```diff
@@ -150,44 +153,50 @@ private void initializeRamseteCommands() {
...
+              oneBallRamseteCommand
+                  .beforeStarting(
+                      () -> driveBaseSubsystem.resetOdometry(oneBallTrajectory.getInitialPose()))
+                  .andThen(() -> driveBaseSubsystem.stopDriveMotors()));
 
       twoBallParallel =
           new ParallelDeadlineGroup(
               twoBallRamseteCommand.beforeStarting(
                   () ->
                       driveBaseSubsystem.resetOdometry(
```
Comment (sarango2158) [inline src/main/java/frc/robot/commands/AutonModes.java:186]: This is the only autonomous mode you have so far that doesn't stop drive motors after resetting odometry. Was that intentional?

File: src/main/java/frc/robot/subsystems/Tabs/TabDriveBase.java [hunk 9]
```diff
@@ -4,7 +4,9 @@
 import edu.wpi.first.networktables.*;
```
Comment (sarango2158) [inline src/main/java/frc/robot/subsystems/Tabs/TabDriveBase.java:4]: More of a general complaint, but this is the only subsystem that uses TabContainers instead of SmartDashboard and/or Shuffleboard directly. The inconsistency makes it harder to maintain.

**Review by sarango2158 — CHANGES_REQUESTED** [review]

File: src/main/java/frc/robot/commands/AutonModes.java (hunk 4 above)
Comment (tonyn10) [reply src/main/java/frc/robot/commands/AutonModes.java:180]: The first ramseteCommand only needs to have resetOdometry to reset the heading so that it matches the path.

File: src/main/java/frc/robot/commands/AutonModes.java (hunk 5 above)
Comment (tonyn10) [reply src/main/java/frc/robot/commands/AutonModes.java:57]: Yes, units are seconds.

File: src/main/java/frc/robot/common/hardware/MotorController.java (hunk 3 above)
Comment (tonyn10) [reply src/main/java/frc/robot/common/hardware/MotorController.java:104]: Extra variable to have clarity purposes.

File: src/main/java/frc/robot/subsystems/Tabs/TabDriveBase.java (hunk 6 above)
Comment (tonyn10) [reply src/main/java/frc/robot/subsystems/Tabs/TabDriveBase.java:55]: If this periodic function is being called in Robot periodic then no need to have it extend SubsystemBase or override.

File: src/main/java/frc/robot/commands/AutonModes.java (hunk 8 above)
Comment (tonyn10) [reply src/main/java/frc/robot/commands/AutonModes.java:186]: No, I forgot to add that. Thanks for the catch!

File: src/main/java/frc/robot/subsystems/Tabs/TabDriveBase.java (hunk 9 above)
Comment (tonyn10) [reply src/main/java/frc/robot/subsystems/Tabs/TabDriveBase.java:4]: We might look to disregard these tabs when competition comes around and standardized our output of data with everyone else. For now it's mainly for our testing purposes.

**Comment by tonyn10** [comment]
@azvanderpas Can you see why the git clean check is failing?

**Comment by azvanderpas** [comment]
> @azvanderpas Can you see why the git clean check is failing?

You need to build your code so Spotless will run and commit the changes. Robot.java has whitespace changes.

**Review by azvanderpas — DISMISSED** [review]

**Review by sarango2158 — APPROVED** [review]
